package no.geonorge.skjema.changelogfile.util;

import java.util.UUID;

import no.geonorge.skjema.sosi.produktspesifikasjon.Arealressurs_45.ArealressursFlateType;
import no.geonorge.skjema.sosi.produktspesifikasjon.Arealressurs_45.ArealressursGrenseType;

/**
 * This interface defines a method for how to convert data from that generated by the provider to the format used in the change log file.
 * 
 * @author lop
 * 
 */

public interface IConvert2ArealressursType {

	/**
	 * Convert the input object to a ArealressursFlateType. The format of the input object is know by the supplier.
	 * The format of ArealressursFlateType is know by the system    
	 *  
	 * @param input
	 * @return 
	 */
	public ArealressursFlateType convert2FlateFromProv(UUID LokalId, Object input);
	
	/**
	 * Convert the input object to a ArealressursGrenseType. The format of the input object is know by the supplier.
	 * The format of ArealressursGrenseType is know by the system    
	 *  
	 * @param input
	 * @return 
	 */
	public ArealressursGrenseType convert2GrenseType(UUID LokalId, Object input);
	
	
	

}
