package no.geonorge.skjema.changelogfile.util;

import no.geonorge.skjema.sosi.produktspesifikasjon.Arealressurs_45.ArealressursFlateType;

/**
 * This interface defines a method for how to convert data from that generated by the provider to the format used in the change log file.
 * 
 * @author lop
 * 
 */

public interface IConvert2ArealressursFlateType {

	/**
	 * Convert the input object to a ArealressursFlateType   
	 *  
	 * @param input
	 * @return 
	 */
	public ArealressursFlateType convert2ArealressursFlateType(Object input);

}
